---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-merge-conflict
  -   id: fix-encoding-pragma
  -   id: check-xml
  -   id: double-quote-string-fixer

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      name: black
      args: ["--skip-string-normalization"]
