coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 80%
        base: auto
        paths:
          - "serde_components"
       # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
