name: Pytest master

on:
  push:
    branches: [ master ]

jobs:
  pytest:
    name: Pytest
    needs: black
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8','3.9','3.10','3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Run Pytest with coverage
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml

  coverage:
    name: Coverage
    needs: pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run Pytest with coverage
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format code with black
        run: |
          pip install black
          black -S --check .
